name: local_notifier
description: This plugin allows Flutter desktop apps to notify local notifications.
version: 0.1.0
homepage: https://github.com/leanflutter/local_notifier

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.4
  osplatform:
     git:
       url: https://github.com/nghuyy/osplatform.git
       ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ngghuy.local_notifier
        pluginClass: LocalNotifierPlugin
      linux:
        pluginClass: LocalNotifierPlugin
      macos:
        pluginClass: LocalNotifierPlugin
      windows:
        pluginClass: LocalNotifierPlugin
